import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '',             loadComponent: () => import('./home/home.component').then(m => m.HomeComponent) },
  { path: 'docs',         loadComponent: () => import('./docs/docs.component').then(m => m.DocsComponent) },
  { path: 'form',         loadComponent: () => import('./form-demo/form-demo.component').then(m => m.FormDemoComponent) },
  { path: 'alert',        loadComponent: () => import('./alert-demo/alert-demo.component').then(m => m.AlertDemoComponent) },
  { path: 'radio-button', loadComponent: () => import('./radio-button-demo/radio-button-demo.component').then(m => m.RadioButtonDemoComponent) },
  { path: 'check-box',    loadComponent: () => import('./check-box-demo/check-box-demo.component').then(m => m.CheckBoxDemoComponent) },
  { path: 'kebab',        loadComponent: () => import('./kebab-demo/kebab-demo.component').then(m => m.KebabDemoComponent) },
  { path: 'button',       loadComponent: () => import('./button-demo/button-demo.component').then(m => m.ButtonDemoComponent) },
  { path: 'onboarding',   loadComponent: () => import('./onboarding-demo/onboarding-demo.component').then(m => m.OnboardingDemoComponent) },
  { path: 'token',        loadComponent: () => import('./token-demo/token-demo.component').then(m => m.TokenDemoComponent) },
  { path: 'chip',         loadComponent: () => import('./chip-demo/chip-demo.component').then(m => m.ChipDemoComponent) },
  { path: 'tooltip',      loadComponent: () => import('./tooltip-demo/tooltip-demo.component').then(m => m.TooltipDemoComponent) },
  { path: 'calendar',     loadComponent: () => import('./calendar-demo/calendar-demo.component').then(m => m.CalendarDemoComponent) },
  { path: 'select',       loadComponent: () => import('./select-demo/select-demo.component').then(m => m.SelectDemoComponent) },
  { path: 'text-input',   loadComponent: () => import('./text-input-demo/text-input-demo.component').then(m => m.TextInputDemoComponent) },
  { path: 'textarea',         loadComponent: () => import('./textarea-demo/textarea-demo.component').then(m => m.TextareaDemoComponent) },
  { path: 'currency-input',   loadComponent: () => import('./currency-input-demo/currency-input-demo.component').then(m => m.CurrencyInputDemoComponent) },
  { path: 'table',            loadComponent: () => import('./table-demo/table-demo.component').then(m => m.TableDemoComponent) },
  { path: 'stepper',          loadComponent: () => import('./stepper-demo/stepper-demo.component').then(m => m.StepperDemoComponent) },
  { path: 'nuevo-empleado',   loadComponent: () => import('./nuevo-empleado/nuevo-empleado.component').then(m => m.NuevoEmpleadoComponent) },
  { path: 'demo-completa',    loadComponent: () => import('./demo-completa/demo-completa.component').then(m => m.DemoCompletaComponent) },
  { path: 'input-date',       loadComponent: () => import('./input-date-demo/input-date-demo.component').then(m => m.InputDateDemoComponent) },
];
